#[cfg_attr(feature = "debug", derive(Debug))]
#[derive(Clone, Copy)]
pub enum Message {
    Quit,
    NextPanel,
    PrevPanel,
    SelectUp,
    SelectDown,
    DirUp,
    DirEnter,
    MarkSelectUp,
    MarkSelectDown,
    ClearSelection,
    TogglePinnedPanel,
    PinCurrentDir,
    SelectPinnedDir,
    DeletePinnedDir,
    EnterFilter,
    FilterChar(char),
    FilterBackspace,
    ConfirmFilter,
    ExitFilter,
    NewPath,
    NewPathChar(char),
    NewPathBackspace,
    NewPathCursorLeft,
    NewPathCursorRight,
    NewPathConfirm,
    NewPathCancel,
    DeleteFiles,
    DeleteConfirm,
    DeleteCancel,
    StartCopy,
    ConfirmCopy,
    CancelCopy,
    StartMove,
    ConfirmMove,
    CancelMove,
    StartCopyRename,
    StartMoveRename,
    RenameInPlace,
    RenameChar(char),
    RenameBackspace,
    RenameCursorLeft,
    RenameCursorRight,
    ConfirmRename,
    CancelRename,
    ToggleHelp,
    OpenEditor,
    OpenDefault,
    CycleSort,
    ZipFiles,
    UnzipFile,
    GotoPath,
    GotoPathChar(char),
    GotoPathBackspace,
    GotoPathCursorLeft,
    GotoPathCursorRight,
    GotoPathConfirm,
    GotoPathCancel,
    ProgressTick {
        current: u64,
        total: u64,
    },
    ProgressDone,
    #[cfg(feature = "debug")]
    ToggleDebug,
}
