#[cfg_attr(feature = "debug", derive(Debug))]
#[derive(Clone, Copy)]
pub enum Message {
    Quit,
    NextPanel,
    PrevPanel,
    SelectUp,
    SelectDown,
    DirUp,
    DirEnter,
    MarkSelectUp,
    MarkSelectDown,
    ClearSelection,
    TogglePinnedPanel,
    PinCurrentDir,
    SelectPinnedDir,
    DeletePinnedDir,
    EnterFilter,
    FilterChar(char),
    FilterBackspace,
    ConfirmFilter,
    ExitFilter,
    FilterBarDown,
    NewPath,
    NewPathChar(char),
    NewPathBackspace,
    NewPathCursorLeft,
    NewPathCursorRight,
    NewPathConfirm,
    NewPathCancel,
    DeleteFiles,
    DeleteConfirm,
    DeleteCancel,
    StartCopy,
    ConfirmCopy,
    CancelCopy,
    StartMove,
    ConfirmMove,
    CancelMove,
    StartCopyRename,
    StartMoveRename,
    RenameInPlace,
    RenameChar(char),
    RenameBackspace,
    RenameCursorLeft,
    RenameCursorRight,
    ConfirmRename,
    CancelRename,
    ToggleHelp,
    HelpScrollUp,
    HelpScrollDown,
    OpenEditor,
    OpenDefault,
    CycleSort,
    ZipFiles,
    UnzipFile,
    GotoPath,
    GotoPathChar(char),
    GotoPathBackspace,
    GotoPathCursorLeft,
    GotoPathCursorRight,
    GotoPathConfirm,
    GotoPathCancel,
    ProgressTick {
        current: u64,
        total: u64,
    },
    ProgressDone,
    OverwriteConfirm,
    OverwriteCancel,
    DismissError,
    ContentSearch,
    ContentSearchChar(char),
    ContentSearchBackspace,
    ContentSearchCursorLeft,
    ContentSearchCursorRight,
    ContentSearchToggleFocus,
    ContentSearchCancel,
    ContentSearchUp,
    ContentSearchDown,
    ContentSearchConfirm,
    FileFind,
    FileFindChar(char),
    FileFindBackspace,
    FileFindCursorLeft,
    FileFindCursorRight,
    FileFindToggleFocus,
    FileFindCancel,
    FileFindUp,
    FileFindDown,
    FileFindConfirm,
    /// Shift was pressed (`true`) or released (`false`); updates the hint bar.
    SetShiftHeld(bool),
    OpenCommandPicker,
    CommandPickerUp,
    CommandPickerDown,
    CommandPickerConfirm,
    CommandPickerCancel,
    CommandInputChar(char),
    CommandInputBackspace,
    CommandInputCursorLeft,
    CommandInputCursorRight,
    CommandInputConfirm,
    CommandInputCancel,
    CapturePopupScrollUp,
    CapturePopupScrollDown,
    CapturePopupPageUp,
    CapturePopupPageDown,
    CapturePopupClose,
    ViewFile,
    FileViewScrollUp,
    FileViewScrollDown,
    FileViewPageUp,
    FileViewPageDown,
    FileViewClose,
    #[cfg(feature = "debug")]
    ToggleDebug,
}

impl Message {
    /// Whether handling this message writes to the filesystem, which makes a
    /// built search index stale. Copies, moves, deletes and renames run in the
    /// background instead and are noticed when their progress finishes.
    pub fn mutates_filesystem(self) -> bool {
        matches!(
            self,
            Self::NewPathConfirm | Self::ZipFiles | Self::UnzipFile
        )
    }
}
